const routes = [
  { path: '/' },
  { path: '/sobre/associacao' },
  { path: '/sobre/historia-guidismo' },
  { path: '/sobre/associacao-mundial'  },
  { path: '/pedagogia/metodo-guidista' },
  { path: '/pedagogia/metodo-guidista/ferramentas/compromisso' },
  { path: '/pedagogia/metodo-guidista/ferramentas/sistema-de-patrulhas' },
  { path: '/pedagogia/metodo-guidista/ferramentas/aprender-fazendo' },
  { path: '/pedagogia/metodo-guidista/ferramentas/auto-desenvolvimento-progressivo' },
  { path: '/pedagogia/metodo-guidista/ferramentas/simbolismo' },
  { path: '/pedagogia/metodo-guidista/ferramentas/cooperação-entre-jovens-e-adultos' },
  { path: '/pedagogia/metodo-guidista/ferramentas/atividades-ao-ar-livre'  },
  { path: '/pedagogia/metodo-guidista/ferramentas/serviço-comunitario' },
  { path: '/pedagogia/metodo-guidista/projetos/ação-saca-rolhas' },
  { path: '/pedagogia/metodo-guidista/projetos/vamos-utopiar' },
  { path: '/pedagogia/metodo-guidista/projetos/portugalta' },
  { path: '/pedagogia/metodo-guidista/projetos/ter-maos-grandes' },
  { path: '/pedagogia/metodo-guidista/projetos/vozes-contra-a-violencia' },
  { path: '/pedagogia/palavra-pais' },
  { path: '/pedagogia/ramo-avezinha' },
  { path: '/pedagogia/ramo-aventura' },
  { path: '/pedagogia/ramo-caravela' },
  { path: '/pedagogia/ramo-moinho' },
  { path: '/pedagogia/dirigente' },
  { path: '/publicações/jornal-trevo' },
  { path: '/publicações/noticias' },
  { path: '/publicações/noticias/1' },
  { path: '/publicações/noticias/2' },
  { path: '/publicações/noticias/3' },
  { path: '/publicações/noticias/4' },
  { path: '/publicações/noticias/5' },
  { path: '/publicações/noticias/6' },
  { path: '/publicações/noticias/7' },
  { path: '/publicações/noticias/8' },
  { path: '/publicações/noticias/9' },
  { path: '/publicações/noticias/10' },
  { path: '/publicações/noticias/11' },
  { path: '/publicações/recursos/ligacoes-uteis' },
  { path: '/loja/livros' },
  { path: '/loja/fardas' },
  { path: '/loja/diversos' },
  { path: '/contactos/sede' },
  { path: '/contactos/formulario' },
  { path: '/search' },
]

/* const routes = [
  { path: '/' },
  { path: '/sobre/associacao' },
  { path: '/sobre/historia-guidismo' },
  { path: '/sobre/associacao-mundial'  },
  { path: '/pedagogia/metodo-guidista' },
  { path: '/pedagogia/metodo-guidista/ferramentas/:ferramenta' },
  { path: '/pedagogia/metodo-guidista/projetos/:projeto' },
  { path: '/pedagogia/palavra-pais' },
  { path: '/pedagogia/:tipo' },
  { path: '/publicações/jornal-trevo' },
  { path: '/publicações/noticias' },
  { path: '/publicações/noticias/:id' },
  { path: '/publicações/recursos/ligacoes-uteis' },
  { path: '/loja/:itemCategory' },
  { path: '/contactos/:modo' },
  { path: '/search' },
] */

module.exports = routes;